/**
 * Trend Micro Deep Security API
 * Copyright 2018 - 2025 Trend Micro Incorporated.<br/>Get protected, stay secured, and keep informed with Trend Micro Deep Security's new RESTful API. Access system data and manage security configurations to automate your security workflows and integrate Deep Security into your CI/CD pipeline. # Authentication <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 20.0.1027
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Deepsecurity) {
      root.Deepsecurity = {};
    }
    root.Deepsecurity.TrustEntityManagementRights = factory(root.Deepsecurity.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The TrustEntityManagementRights model module.
   * @module model/TrustEntityManagementRights
   * @version 20.0.1027
   */

  /**
   * Constructs a new <code>TrustEntityManagementRights</code>.
   * Trust entity management details.
   * @alias module:model/TrustEntityManagementRights
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>TrustEntityManagementRights</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TrustEntityManagementRights} obj Optional instance to populate.
   * @return {module:model/TrustEntityManagementRights} The populated <code>TrustEntityManagementRights</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('canCreateAppControlTrustEntities')) {
        obj['canCreateAppControlTrustEntities'] = ApiClient.convertToType(data['canCreateAppControlTrustEntities'], 'Boolean');
      }
      if (data.hasOwnProperty('canViewAppControlTrustEntities')) {
        obj['canViewAppControlTrustEntities'] = ApiClient.convertToType(data['canViewAppControlTrustEntities'], 'Boolean');
      }
      if (data.hasOwnProperty('canEditAppControlTrustEntities')) {
        obj['canEditAppControlTrustEntities'] = ApiClient.convertToType(data['canEditAppControlTrustEntities'], 'Boolean');
      }
      if (data.hasOwnProperty('canDeleteAppControlTrustEntities')) {
        obj['canDeleteAppControlTrustEntities'] = ApiClient.convertToType(data['canDeleteAppControlTrustEntities'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * Right to create entities in the trust entity management.
   * @member {Boolean} canCreateAppControlTrustEntities
   */
  exports.prototype['canCreateAppControlTrustEntities'] = undefined;
  /**
   * Right to view entities in the trust entity management.
   * @member {Boolean} canViewAppControlTrustEntities
   */
  exports.prototype['canViewAppControlTrustEntities'] = undefined;
  /**
   * Right to edit entities in the trust entity management.
   * @member {Boolean} canEditAppControlTrustEntities
   */
  exports.prototype['canEditAppControlTrustEntities'] = undefined;
  /**
   * Right to delete entities in the trust entity management.
   * @member {Boolean} canDeleteAppControlTrustEntities
   */
  exports.prototype['canDeleteAppControlTrustEntities'] = undefined;



  return exports;
}));



